//! CP/DP gRPC communication layer.
//!
//! The `ConfigSync` service (defined in `proto/ferrum.proto`) provides:
//! - `Subscribe` — server-streaming RPC for real-time config updates
//! - `GetFullConfig` — unary RPC for on-demand config snapshots
//!
//! Authentication uses HS256 JWT in the `authorization` gRPC metadata key.
//! Proto types are code-generated by `tonic_build` from `proto/ferrum.proto`
//! at compile time (see `build.rs`).

pub mod cp_server;
pub mod dp_client;

pub mod proto {
    tonic::include_proto!("ferrum");
}
