use std::env;
use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_protos(&["proto/ferrum.proto"], &["proto/"])?;

    tonic_build::compile_protos("proto/health.proto")?;

    // ── Auto-discover custom plugins ────────────────────────────────────
    //
    // Scans custom_plugins/*.rs for files that export a `create_plugin`
    // function and generates the module declarations, factory match arms,
    // and name list automatically.
    //
    // Users just drop a .rs file in custom_plugins/ and rebuild — no
    // registry file to edit.

    let custom_dir = Path::new("custom_plugins");
    let out_dir = env::var("OUT_DIR")?;

    // Collect plugin file names (excluding mod.rs)
    let mut plugin_names: Vec<String> = Vec::new();

    if custom_dir.is_dir() {
        // If FERRUM_CUSTOM_PLUGINS is set, only include those plugins.
        // Otherwise, include all .rs files in the directory.
        let filter: Option<Vec<String>> = env::var("FERRUM_CUSTOM_PLUGINS")
            .ok()
            .map(|v| v.split(',').map(|s| s.trim().to_string()).collect());

        for entry in fs::read_dir(custom_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "rs") {
                let stem = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("")
                    .to_string();
                if stem == "mod" {
                    continue;
                }
                if let Some(ref allowed) = filter
                    && !allowed.contains(&stem)
                {
                    continue;
                }
                plugin_names.push(stem);
            }
        }
    }

    plugin_names.sort();

    // Generate module declarations with absolute #[path] attributes so the
    // compiler finds the source files in custom_plugins/ (not in OUT_DIR).
    let custom_dir_abs = fs::canonicalize(custom_dir)?;
    let mut mods = String::new();
    for name in &plugin_names {
        let plugin_path = custom_dir_abs.join(format!("{}.rs", name));
        let path_str = plugin_path.display().to_string().replace('\\', "/");
        mods.push_str(&format!("#[path = \"{}\"]\npub mod {};\n", path_str, name));
    }
    fs::write(Path::new(&out_dir).join("custom_plugin_mods.rs"), &mods)?;

    // Generate factory and discovery functions
    use std::fmt::Write;
    let mut registry = String::new();
    writeln!(
        registry,
        "/// Create a custom plugin instance by name (auto-generated by build.rs)."
    )?;
    writeln!(registry, "pub fn create_custom_plugin(")?;
    writeln!(registry, "    name: &str,")?;
    writeln!(registry, "    config: &serde_json::Value,")?;
    writeln!(
        registry,
        "    http_client: crate::plugins::PluginHttpClient,"
    )?;
    writeln!(
        registry,
        ") -> Option<std::sync::Arc<dyn crate::plugins::Plugin>> {{"
    )?;
    writeln!(registry, "    match name {{")?;
    for name in &plugin_names {
        writeln!(
            registry,
            "        \"{}\" => {}::create_plugin(config, http_client),",
            name, name
        )?;
    }
    writeln!(registry, "        _ => None,")?;
    writeln!(registry, "    }}")?;
    writeln!(registry, "}}")?;
    writeln!(registry)?;
    writeln!(
        registry,
        "/// Returns the names of all registered custom plugins (auto-generated by build.rs)."
    )?;
    writeln!(
        registry,
        "pub fn custom_plugin_names() -> Vec<&'static str> {{"
    )?;
    writeln!(registry, "    vec![")?;
    for name in &plugin_names {
        writeln!(registry, "        \"{}\",", name)?;
    }
    writeln!(registry, "    ]")?;
    writeln!(registry, "}}")?;

    fs::write(
        Path::new(&out_dir).join("custom_plugin_registry.rs"),
        &registry,
    )?;

    // Re-run build script when custom_plugins/ changes
    println!("cargo:rerun-if-changed=custom_plugins/");
    println!("cargo:rerun-if-env-changed=FERRUM_CUSTOM_PLUGINS");

    Ok(())
}
