apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh-control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.ambient.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh-ambient
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh-ambient
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.eastWest.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh-east-west
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh-east-west
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.injector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.ca.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh-ca
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
