//! Built-in plugin documentation/parity metadata.
//!
//! Priority and live protocol attachment come from each plugin's `Plugin`
//! implementation. This module carries the remaining machine-readable fields
//! needed to keep `docs/plugin_execution_order.md` set-equal with
//! [`crate::plugins::BUILTIN_PLUGIN_REGISTRATIONS`]: classification,
//! documented active phases, protocol-matrix capability surface, and rationale.

use super::{
    ALL_PROTOCOLS, GRPC_ONLY_PROTOCOLS, HTTP_FAMILY_PROTOCOLS, HTTP_GRPC_PROTOCOLS,
    HTTP_ONLY_PROTOCOLS, ProxyProtocol, TCP_ONLY_PROTOCOLS, UDP_ONLY_PROTOCOLS, WS_ONLY_PROTOCOLS,
};

/// How a built-in plugin appears in public inventories.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinPluginClassification {
    /// Ordinary operator-facing plugin with lifecycle hooks.
    Public,
    /// Reserved internal name; typically auto-injected by mesh runtime.
    Reserved,
    /// Config-only: cache/schema registration ordering with no request hooks.
    ConfigOnly,
}

/// Canonical documentation/parity metadata for one built-in plugin.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BuiltinPluginParityMeta {
    pub name: &'static str,
    pub classification: BuiltinPluginClassification,
    /// Priority matching the Complete Execution Order table and `Plugin::priority()`.
    pub priority: u16,
    /// Active-phases cell from the Complete Execution Order table.
    pub active_phases: &'static str,
    /// Protocol capability surface documented in the protocol matrix.
    /// Empty means config-only / not protocol-applicable (`—` cells).
    pub matrix_protocols: &'static [ProxyProtocol],
    /// Rationale cell from the protocol matrix.
    pub protocol_rationale: &'static str,
}

/// Machine-readable parity metadata for every built-in plugin.
///
/// Must stay set-equal with [`super::BUILTIN_PLUGIN_REGISTRATIONS`]. Priority
/// values must match each plugin's `Plugin::priority()`; matrix protocols must
/// match `Plugin::supported_protocols()` for a minimal config except where the
/// rationale documents a config-dependent capability envelope (currently `waf`).
pub const BUILTIN_PLUGIN_PARITY_META: &[BuiltinPluginParityMeta] = &[
    BuiltinPluginParityMeta {
        name: "otel_tracing",
        classification: BuiltinPluginClassification::Public,
        priority: 25,
        active_phases: "on_request_received, on_stream_connect, before_proxy, after_proxy, log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Tracing for all protocols",
    },
    BuiltinPluginParityMeta {
        name: "correlation_id",
        classification: BuiltinPluginClassification::Public,
        priority: 50,
        active_phases: "on_request_received, before_proxy, after_proxy, apply_websocket_handshake_response_headers, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "ID assignment is protocol-agnostic",
    },
    BuiltinPluginParityMeta {
        name: "cors",
        classification: BuiltinPluginClassification::Public,
        priority: 100,
        active_phases: "on_request_received, after_proxy",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Origin/ACAO enforcement includes browser gRPC-Web requests",
    },
    BuiltinPluginParityMeta {
        name: "request_termination",
        classification: BuiltinPluginClassification::Public,
        priority: 125,
        active_phases: "on_request_received",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Returns HTTP error response",
    },
    BuiltinPluginParityMeta {
        name: "mesh_outbound_registry",
        classification: BuiltinPluginClassification::Public,
        priority: 130,
        active_phases: "on_request_received",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Host-header outbound registry gating is HTTP-family only; raw streams use mesh connect/datagram enforcement",
    },
    BuiltinPluginParityMeta {
        name: "ip_restriction",
        classification: BuiltinPluginClassification::Public,
        priority: 150,
        active_phases: "on_request_received, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "IP filtering is protocol-agnostic",
    },
    BuiltinPluginParityMeta {
        name: "geo_restriction",
        classification: BuiltinPluginClassification::Public,
        priority: 175,
        active_phases: "on_request_received, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "GeoIP country allow/deny is protocol-agnostic",
    },
    BuiltinPluginParityMeta {
        name: "bot_detection",
        classification: BuiltinPluginClassification::Public,
        priority: 200,
        active_phases: "on_request_received",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Needs User-Agent header",
    },
    BuiltinPluginParityMeta {
        name: "spec_expose",
        classification: BuiltinPluginClassification::Public,
        priority: 210,
        active_phases: "on_request_received",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only; requires prefix listen_path",
    },
    BuiltinPluginParityMeta {
        name: "sse",
        classification: BuiltinPluginClassification::Public,
        priority: 250,
        active_phases: "on_request_received, before_proxy, after_proxy, transform_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "SSE is HTTP-only (text/event-stream over chunked transfer)",
    },
    BuiltinPluginParityMeta {
        name: "grpc_web",
        classification: BuiltinPluginClassification::Public,
        priority: 260,
        active_phases: "on_request_received, before_proxy, transform_request_body, on_final_request_body, after_proxy, transform_response_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Translates gRPC-Web (browser) ↔ native gRPC (HTTP/2)",
    },
    BuiltinPluginParityMeta {
        name: "grpc_method_router",
        classification: BuiltinPluginClassification::Public,
        priority: 275,
        active_phases: "on_request_received, on_backend_path_resolved",
        matrix_protocols: GRPC_ONLY_PROTOCOLS,
        protocol_rationale: "gRPC method-level access control and rate limiting",
    },
    BuiltinPluginParityMeta {
        name: "spiffe_identity",
        classification: BuiltinPluginClassification::Public,
        priority: 940,
        active_phases: "on_request_received, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Extracts SPIFFE IDs from TLS/DTLS client certificates",
    },
    BuiltinPluginParityMeta {
        name: "mtls_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 950,
        active_phases: "authenticate, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Requires TLS/DTLS client certificate",
    },
    BuiltinPluginParityMeta {
        name: "jwks_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1000,
        active_phases: "authenticate",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP headers",
    },
    BuiltinPluginParityMeta {
        name: "oauth2_introspection",
        classification: BuiltinPluginClassification::Public,
        priority: 1050,
        active_phases: "authenticate, before_proxy",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP bearer token headers or query params",
    },
    BuiltinPluginParityMeta {
        name: "oidc_relying_party",
        classification: BuiltinPluginClassification::Public,
        priority: 1075,
        active_phases: "authenticate, before_proxy",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Browser-oriented HTTP authentication flow",
    },
    BuiltinPluginParityMeta {
        name: "jwt_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1100,
        active_phases: "authenticate",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP headers",
    },
    BuiltinPluginParityMeta {
        name: "key_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1200,
        active_phases: "authenticate, before_proxy",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP headers or query parameters",
    },
    BuiltinPluginParityMeta {
        name: "ldap_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1250,
        active_phases: "authenticate",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP Basic auth header; authenticates against LDAP directory",
    },
    BuiltinPluginParityMeta {
        name: "basic_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1300,
        active_phases: "authenticate",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP headers",
    },
    BuiltinPluginParityMeta {
        name: "hmac_auth",
        classification: BuiltinPluginClassification::Public,
        priority: 1400,
        active_phases: "authenticate",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Requires HTTP headers and a buffered request body; HBONE CONNECT fails closed as incompatible",
    },
    BuiltinPluginParityMeta {
        name: "soap_ws_security",
        classification: BuiltinPluginClassification::Public,
        priority: 1500,
        active_phases: "authenticate, before_proxy, on_final_request_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "SOAP XML body parsing (text/xml, application/soap+xml, application/xml, application/xop+xml, MTOM multipart/related)",
    },
    BuiltinPluginParityMeta {
        name: "access_control",
        classification: BuiltinPluginClassification::Public,
        priority: 2000,
        active_phases: "authorize, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Needs authenticated identity from an auth plugin; supports consumer username and ACL group allow/deny lists",
    },
    BuiltinPluginParityMeta {
        name: "tcp_connection_throttle",
        classification: BuiltinPluginClassification::Public,
        priority: 2050,
        active_phases: "on_stream_connect (opaque connection permit releases on rejection/teardown)",
        matrix_protocols: TCP_ONLY_PROTOCOLS,
        protocol_rationale: "Tracks process-local active TCP/TCP+TLS connections per Consumer or canonical client IP; each replica enforces independently",
    },
    BuiltinPluginParityMeta {
        name: "mesh_authz",
        classification: BuiltinPluginClassification::Public,
        priority: 2075,
        active_phases: "authorize, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Applies Layer 2 mesh policy using SPIFFE or HBONE identities",
    },
    BuiltinPluginParityMeta {
        name: "opa",
        classification: BuiltinPluginClassification::Public,
        priority: 2080,
        active_phases: "authorize",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "Delegates HTTP request authorization to an OPA Data API policy",
    },
    BuiltinPluginParityMeta {
        name: "adaptive_concurrency",
        classification: BuiltinPluginClassification::Public,
        priority: 2090,
        active_phases: "backend_admission",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Target-aware backend admission for HTTP-family upstream survival",
    },
    BuiltinPluginParityMeta {
        name: "request_deduplication",
        classification: BuiltinPluginClassification::Public,
        priority: 3010,
        active_phases: "before_proxy, on_final_response_body, on_response_stream_terminated",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only request deduplication and response replay",
    },
    BuiltinPluginParityMeta {
        name: "request_size_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 2800,
        active_phases: "on_request_received, before_proxy, on_final_request_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Enforces per-proxy request body size limits",
    },
    BuiltinPluginParityMeta {
        name: "ws_message_size_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 2810,
        active_phases: "parser-level frame/message limits",
        matrix_protocols: WS_ONLY_PROTOCOLS,
        protocol_rationale: "Enforces actual-frame and bounded-reassembly limits on WebSocket connections",
    },
    BuiltinPluginParityMeta {
        name: "graphql",
        classification: BuiltinPluginClassification::Public,
        priority: 2850,
        active_phases: "before_proxy",
        matrix_protocols: &[ProxyProtocol::Http, ProxyProtocol::WebSocket],
        protocol_rationale: "GraphQL JSON over HTTP and GraphQL subscriptions over WebSocket",
    },
    BuiltinPluginParityMeta {
        name: "rate_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 2900,
        active_phases: "on_request_received (IP mode), authorize (consumer mode), before_proxy, after_proxy, on_stream_connect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Connection/session rate applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "ws_rate_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 2910,
        active_phases: "on_ws_frame, on_ws_reassembly_frames",
        matrix_protocols: WS_ONLY_PROTOCOLS,
        protocol_rationale: "Per-connection frame rate limiting for WebSocket",
    },
    BuiltinPluginParityMeta {
        name: "udp_rate_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 2915,
        active_phases: "on_udp_datagram",
        matrix_protocols: UDP_ONLY_PROTOCOLS,
        protocol_rationale: "Per-client-IP datagram and byte rate limiting for UDP proxies",
    },
    BuiltinPluginParityMeta {
        name: "ai_transcript_audit",
        classification: BuiltinPluginClassification::Public,
        priority: 2740,
        active_phases: "before_proxy, on_final_request_body, on_final_response_body, on_response_committed, response_stream_inspector, on_response_stream_terminated, log",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only AI transcript capture to a configured sink",
    },
    BuiltinPluginParityMeta {
        name: "ai_prompt_shield",
        classification: BuiltinPluginClassification::Public,
        priority: 2925,
        active_phases: "before_proxy, transform_request_body, on_final_request_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only PII detection/redaction for bare JSON prompts; native gRPC unsupported (gRPC-Web framed bodies are skipped)",
    },
    BuiltinPluginParityMeta {
        name: "waf",
        classification: BuiltinPluginClassification::Public,
        priority: 2930,
        active_phases: "authorize, on_final_request_body, after_proxy, on_final_response_body, on_stream_connect, on_udp_datagram",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "HTTP-family always; TCP/UDP first-bytes and datagram inspection when a `stream` block is configured",
    },
    BuiltinPluginParityMeta {
        name: "fault_injection",
        classification: BuiltinPluginClassification::Public,
        priority: 2940,
        active_phases: "before_proxy, on_stream_connect, on_udp_datagram",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Probabilistic aborts and delays across HTTP-family, TCP stream connect, and UDP/DTLS session + datagram hooks",
    },
    BuiltinPluginParityMeta {
        name: "body_validator",
        classification: BuiltinPluginClassification::Public,
        priority: 2950,
        active_phases: "before_proxy, on_final_request_body, after_proxy, on_final_response_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Validates request and response bodies",
    },
    BuiltinPluginParityMeta {
        name: "openapi_validator",
        classification: BuiltinPluginClassification::Public,
        priority: 2960,
        active_phases: "validate_client_request_body_contract, before_proxy, on_final_request_body, after_proxy, on_final_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "Validates bodies against generated OpenAPI operation schemas",
    },
    BuiltinPluginParityMeta {
        name: "ai_semantic_firewall",
        classification: BuiltinPluginClassification::Public,
        priority: 2968,
        active_phases: "before_proxy, on_final_request_body, on_response_body, on_final_response_body, response_stream_inspector, on_response_stream_terminated",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only semantic inspection for LLM JSON request and response bodies",
    },
    BuiltinPluginParityMeta {
        name: "ai_request_guard",
        classification: BuiltinPluginClassification::Public,
        priority: 2975,
        active_phases: "before_proxy, transform_request_body, on_final_request_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Validates JSON request bodies",
    },
    BuiltinPluginParityMeta {
        name: "ai_tool_governor",
        classification: BuiltinPluginClassification::Public,
        priority: 2978,
        active_phases: "before_proxy, on_final_request_body, on_response_body, transform_response_body, on_final_response_body, response_stream_inspector, on_response_stream_terminated",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only deterministic tool/function-call policy on JSON and SSE bodies",
    },
    BuiltinPluginParityMeta {
        name: "ai_stream_router",
        classification: BuiltinPluginClassification::Public,
        priority: 2984,
        active_phases: "before_proxy, transform_request_body, normalize_response_body, response_stream_inspector",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "Claims `stream: true` OpenAI Chat Completions, route-overrides to a provider, normalizes provider SSE to OpenAI SSE",
    },
    BuiltinPluginParityMeta {
        name: "mcp_gateway",
        classification: BuiltinPluginClassification::Public,
        priority: 2992,
        active_phases: "before_proxy, transform_request_body, transform_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only MCP JSON-RPC parsing, metadata, and namespaced tool/resource/prompt routing",
    },
    BuiltinPluginParityMeta {
        name: "a2a_gateway",
        classification: BuiltinPluginClassification::Public,
        priority: 2993,
        active_phases: "before_proxy, after_proxy, on_response_body, response_stream_inspector",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Detects A2A HTTP/REST/gRPC methods, rewrites HTTP Agent Cards, applies method policy, and emits `a2a.*` metadata",
    },
    BuiltinPluginParityMeta {
        name: "mesh_route_dispatch",
        classification: BuiltinPluginClassification::Public,
        priority: 2995,
        active_phases: "before_proxy",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "Rewrites the routing decision per request via `RequestContext.route_override_*`; for WebSocket, selects the upgrade backend only, not per-frame routing",
    },
    BuiltinPluginParityMeta {
        name: "request_transformer",
        classification: BuiltinPluginClassification::Public,
        priority: 3000,
        active_phases: "before_proxy, transform_request_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Modifies HTTP headers/query/body",
    },
    BuiltinPluginParityMeta {
        name: "serverless_function",
        classification: BuiltinPluginClassification::Public,
        priority: 3025,
        active_phases: "finalized request egress",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Invokes cloud functions (AWS Lambda, Azure Functions, GCP Cloud Functions); terminate supports HTTP and native unary gRPC",
    },
    BuiltinPluginParityMeta {
        name: "response_mock",
        classification: BuiltinPluginClassification::Public,
        priority: 3030,
        active_phases: "before_proxy",
        matrix_protocols: &[ProxyProtocol::Http, ProxyProtocol::WebSocket],
        protocol_rationale: "Short-circuits HTTP and WebSocket upgrade handshakes; native gRPC unsupported by design — only the validated serverless_function terminate contract carries provenance-authorized framed unary Reject semantics",
    },
    BuiltinPluginParityMeta {
        name: "grpc_deadline",
        classification: BuiltinPluginClassification::Public,
        priority: 3050,
        active_phases: "receipt-time deadline preflight, before_proxy",
        matrix_protocols: GRPC_ONLY_PROTOCOLS,
        protocol_rationale: "gRPC timeout enforcement and propagation",
    },
    BuiltinPluginParityMeta {
        name: "load_testing",
        classification: BuiltinPluginClassification::Public,
        priority: 3070,
        active_phases: "before_proxy",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "On-demand load testing via header trigger with multi-node fan-out",
    },
    BuiltinPluginParityMeta {
        name: "request_mirror",
        classification: BuiltinPluginClassification::Public,
        priority: 3075,
        active_phases: "authorize (pre-buffer mirror admission; never rejects), finalized request egress",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Duplicates traffic to a shadow destination for validation",
    },
    BuiltinPluginParityMeta {
        name: "response_size_limiting",
        classification: BuiltinPluginClassification::Public,
        priority: 3490,
        active_phases: "after_proxy, on_final_response_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Enforces per-proxy response body size limits",
    },
    BuiltinPluginParityMeta {
        name: "response_caching",
        classification: BuiltinPluginClassification::Public,
        priority: 3500,
        active_phases: "before_proxy, after_proxy, on_final_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only response cache lookup and store",
    },
    BuiltinPluginParityMeta {
        name: "response_transformer",
        classification: BuiltinPluginClassification::Public,
        priority: 4000,
        active_phases: "after_proxy, transform_response_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "Modifies HTTP response headers/body",
    },
    BuiltinPluginParityMeta {
        name: "compression",
        classification: BuiltinPluginClassification::Public,
        priority: 4050,
        active_phases: "normalize_buffered_request_body_before_before_proxy, before_proxy, after_proxy, transform_request_body, transform_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP response compression and request decompression (gzip, brotli)",
    },
    BuiltinPluginParityMeta {
        name: "ai_prompt_compressor",
        classification: BuiltinPluginClassification::Public,
        priority: 4055,
        active_phases: "before_proxy, transform_request_body_with_context, on_final_request_body_with_context",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only JSON prompt compression; native gRPC wire frames are not rewritten",
    },
    BuiltinPluginParityMeta {
        name: "ai_semantic_cache",
        classification: BuiltinPluginClassification::Public,
        priority: 4057,
        active_phases: "on_final_request_body_with_context, after_proxy, on_final_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only exact/semantic cache for LLM JSON request and response bodies",
    },
    BuiltinPluginParityMeta {
        name: "ai_federation",
        classification: BuiltinPluginClassification::Public,
        priority: 4060,
        active_phases: "finalized request egress (HTTP only)",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP-only; routes final OpenAI JSON bodies to providers and normalizes bounded responses",
    },
    BuiltinPluginParityMeta {
        name: "ai_response_guard",
        classification: BuiltinPluginClassification::Public,
        priority: 4075,
        active_phases: "after_proxy, on_response_body, transform_response_body",
        matrix_protocols: HTTP_GRPC_PROTOCOLS,
        protocol_rationale: "HTTP JSON/SSE/text response inspection; native gRPC only for methods enrolled in the descriptor-based `grpc` block",
    },
    BuiltinPluginParityMeta {
        name: "security_headers",
        classification: BuiltinPluginClassification::Public,
        priority: 4080,
        active_phases: "after_proxy, initial response-header boundary",
        matrix_protocols: HTTP_FAMILY_PROTOCOLS,
        protocol_rationale: "HTTP-family response security headers and fingerprint stripping",
    },
    BuiltinPluginParityMeta {
        name: "ai_token_metrics",
        classification: BuiltinPluginClassification::Public,
        priority: 4100,
        active_phases: "on_response_body",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP JSON/SSE accounting only; native gRPC protobuf has no supported provider schema contract",
    },
    BuiltinPluginParityMeta {
        name: "ai_rate_limiter",
        classification: BuiltinPluginClassification::Public,
        priority: 4200,
        active_phases: "before_proxy, on_final_request_body, after_proxy, on_response_body, response_stream_inspector, on_response_stream_terminated",
        matrix_protocols: HTTP_ONLY_PROTOCOLS,
        protocol_rationale: "HTTP JSON/SSE token accounting only; native gRPC protobuf frames have no supported usage schema, so gRPC attachment would never charge",
    },
    BuiltinPluginParityMeta {
        name: "stdout_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9000,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "ws_frame_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9050,
        active_phases: "on_ws_frame",
        matrix_protocols: WS_ONLY_PROTOCOLS,
        protocol_rationale: "Logs WebSocket frame metadata",
    },
    BuiltinPluginParityMeta {
        name: "statsd_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9075,
        active_phases: "log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "http_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9100,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "tcp_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9125,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "kafka_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9150,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "loki_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9155,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "udp_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9160,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "ws_logging",
        classification: BuiltinPluginClassification::Public,
        priority: 9175,
        active_phases: "log, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "transaction_debugger",
        classification: BuiltinPluginClassification::Public,
        priority: 9200,
        active_phases: "on_request_received, before_proxy, on_final_request_body, after_proxy, on_final_response_body, log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Observability applies everywhere",
    },
    BuiltinPluginParityMeta {
        name: "proxy_alerts",
        classification: BuiltinPluginClassification::Public,
        priority: 9250,
        active_phases: "log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Anomaly notifications across all protocols",
    },
    BuiltinPluginParityMeta {
        name: "prometheus_metrics",
        classification: BuiltinPluginClassification::Public,
        priority: 9300,
        active_phases: "log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Metrics for all protocols",
    },
    BuiltinPluginParityMeta {
        name: "api_chargeback",
        classification: BuiltinPluginClassification::Public,
        priority: 9350,
        active_phases: "log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "In-memory charge accumulator for HTTP-family, WebSocket bandwidth, and stream sessions",
    },
    BuiltinPluginParityMeta {
        name: "api_chargeback_sink",
        classification: BuiltinPluginClassification::Public,
        priority: 9351,
        active_phases: "log, on_stream_disconnect, on_ws_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Durable ClickHouse charge event/snapshot exporter",
    },
    BuiltinPluginParityMeta {
        name: "workload_metrics",
        classification: BuiltinPluginClassification::Public,
        priority: 9360,
        active_phases: "on_request_received, before_proxy, after_proxy, log, on_stream_connect, on_stream_disconnect",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Adds Istio/GAMMA mesh identity labels to metadata",
    },
    BuiltinPluginParityMeta {
        name: "__mesh_bpf_metrics",
        classification: BuiltinPluginClassification::Reserved,
        priority: 9365,
        active_phases: "(no lifecycle hooks; passive Prometheus surface populated by the BPF SOCK_OPS event consumer)",
        matrix_protocols: ALL_PROTOCOLS,
        protocol_rationale: "Reserved/auto-injected NodeWaypoint BPF SOCK_OPS Prometheus surface (counters + fixed latency histograms); no request hooks",
    },
    BuiltinPluginParityMeta {
        name: "transaction_log_schema",
        classification: BuiltinPluginClassification::ConfigOnly,
        priority: 9999,
        active_phases: "(config-only; no lifecycle hooks — priority retained for schema-registration inventory/order)",
        matrix_protocols: &[],
        protocol_rationale: "Config-only: registers named log schemas during cache rebuild; no protocol hooks (ordering priority 9999)",
    },
];

pub fn builtin_plugin_parity_meta(name: &str) -> Option<&'static BuiltinPluginParityMeta> {
    BUILTIN_PLUGIN_PARITY_META
        .iter()
        .find(|entry| entry.name == name)
}
